title: Hola, soy Ale
description: Sitio personal y profesional de Alejandro Sirioni (ux designer & dev)
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Alejandro Gabriel Sirioni # add your name
author-img: david-freeman.jpg # add your photo
about-author: UX / UI Designer. Developer. Dinámico, amante de la tecnología y la creatividad.  
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: alejandro-sirioni # add your Linkedin handle
social-email: alejandrosirioni@gmail.com # add your Email address
social-dribbble: asirioni # add your Email address

# Disqus
discus-identifier: Ale # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
